version: '3'

services:

  myapp-web:
    image: nginx:1.21.1
    container_name: myapp-web
    restart: unless-stopped
    ports:
      - 8080:80
    labels:
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/module=nginx"
      - "co.elastic.logs/fileset.stdout=access"
      - "co.elastic.logs/fileset.stderr=error"


  myapp-with-customlog:
    image: ubuntu
    container_name: myapp-with-customlog
    restart: unless-stopped
    volumes:
      - ./custom-log-generator.sh:/custom-log-generator.sh
    command: /custom-log-generator.sh
    labels:
      - "co.elastic.logs/enabled=true"


  filebeat-docker-monitoring:
    image: docker.elastic.co/beats/filebeat:7.13.4
    container_name: filebeat-docker-monitoring
    restart: unless-stopped
    user: root
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-node1}
      - KIBANA_HOST=${KIBANA_HOST:-node1}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    command: ["--strict.perms=false"]
    networks:
      - filebeat-example

networks:
  filebeat-example:
    name: filebeat-example
